// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

const (
	StateStart    = "start" // 面试开始
	StateQuestion = "question" // 核心问题阶段
	StateFollowUp = "follow_up" // 追问深入阶段
	StateEvaluate = "evaluate" // 评估总结阶段
	StateEnd      = "end" //面试结束
)

type ChatResponse struct {
	Content string `json:"content"`
	IsLast  bool   `json:"isLast"`
}

type InterviewAPPChatReq struct {
	Message string `form:"message"`
	ChatId  string `form:"chatId"`
}
